[package]
name = "ripgrepclone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.3"
regex = "1.8.1"
ansi_term = "0.12.1"
